# Generated by Django 2.2.6 on 2019-10-29 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='dum',
        ),
    ]
