# Generated by Django 2.2.6 on 2019-11-04 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_remove_task_dum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='owner',
        ),
    ]
