# Generated by Django 2.2.6 on 2019-11-05 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20191104_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='folder',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='folder.Folder'),
        ),
    ]
